abort build if no success after all the retries

diff --git a/.github/workflows/bundle-ucm.yaml b/.github/workflows/bundle-ucm.yaml
--- a/.github/workflows/bundle-ucm.yaml
+++ b/.github/workflows/bundle-ucm.yaml
@@ -62,7 +62,10 @@ jobs:
                 --flag unison-runtime:optchecks \
                 && break;
           done
-
+          if [[ $i -eq $tries ]]; then
+              echo "Failed to build unison after $tries tries"
+              exit 1
+          fi
           if [[ ${{runner.os}} = 'Windows' ]]; then
             ucm=$(stack exec where unison)
           else
